
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 19 22:21:34 CST 2019
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int finIns = 6;
  public static final int clas = 8;
  public static final int definicionDeMetodo = 17;
  public static final int decimal = 22;
  public static final int els = 12;
  public static final int instruccion = 19;
  public static final int iszero = 10;
  public static final int iterate = 14;
  public static final int progra = 9;
  public static final int parenC = 5;
  public static final int parenA = 4;
  public static final int operador = 18;
  public static final int llaveC = 3;
  public static final int EOF = 0;
  public static final int llaveA = 2;
  public static final int iff = 11;
  public static final int negacion = 7;
  public static final int whil = 13;
  public static final int error = 1;
  public static final int funcionBooleana = 20;
  public static final int operacion = 16;
  public static final int ret = 15;
  public static final int identificador = 21;
}

